### ISSUE TITLE
Deprecation warning because of ActionUpdateThread.OLD_EDT in IntelliJ IDEA 2024.1

### ISSUE THREAD

**Issue by daalla** [pnbarx/idea-treecolor#19]
Hi all! I wanted to let you know that IntelliJ IDEA 2024.1 is showing a warning probably because the plugin is using a deprecated element, `ActionUpdateThread.OLD_EDT`. Please let me know if I can help with something to solve this warning. Thanks!

Plugin version: ProjectTree Color Highlighter 1.2.2

Stacktrace:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'dev.pnbarx.idea.treecolor.actions.HighlightActionGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.pnbarx.idea.treecolor]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

Screenshot of the warning:
![image](https://github.com/pnbarx/idea-treecolor/assets/49034810/f26c4226-c1d0-4a89-a530-297e24cccaad)

**Comment by nullkat** [comment]
Fixed it. I will make pull request soon.

**Comment by daalla** [comment]
Thank you very much :)

**Comment by ilmirons** [comment]
+1 on this issue

**Comment by richtrefz** [comment]
+1 on this issue
