### ISSUE TITLE
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated 

### ISSUE THREAD

**Issue by lougxing** [pnbarx/idea-treecolor#23]
Hi， I have a problem， please help me.

version：
Goland 2024.2.3

Question：

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'dev.pnbarx.idea.treecolor.actions.HighlightActionGroup' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.pnbarx.idea.treecolor]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by nullkat** [comment]
hey. duplicate: https://github.com/pnbarx/idea-treecolor/issues/19

 it is plugin issue, not yours
